[2023-04-14T22:14:19.008+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pads.launchpad scheduled__2023-01-01T01:15:00+00:00 [queued]>
[2023-04-14T22:14:19.165+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pads.launchpad scheduled__2023-01-01T01:15:00+00:00 [queued]>
[2023-04-14T22:14:19.168+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:14:19.171+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-14T22:14:19.178+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:14:19.409+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): launchpad> on 2023-01-01 01:15:00+00:00
[2023-04-14T22:14:19.471+0000] {standard_task_runner.py:55} INFO - Started process 457 to run task
[2023-04-14T22:14:19.510+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pads', 'launchpad', 'scheduled__2023-01-01T01:15:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi5n4pntx']
[2023-04-14T22:14:19.550+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask launchpad
[2023-04-14T22:14:20.218+0000] {task_command.py:389} INFO - Running <TaskInstance: pads.launchpad scheduled__2023-01-01T01:15:00+00:00 [running]> on host a0b8dfb9f67f
[2023-04-14T22:14:20.945+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Amogh Srigopal
AIRFLOW_CTX_DAG_ID=pads
AIRFLOW_CTX_TASK_ID=launchpad
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T01:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T01:15:00+00:00
[2023-04-14T22:14:20.975+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T22:14:20.979+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/amoghsrigopal/Downloads/SpaceDataPipeline/launchpad.py']
[2023-04-14T22:14:21.051+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T22:14:21.798+0000] {subprocess.py:93} INFO - python: can't open file '/Users/amoghsrigopal/Downloads/SpaceDataPipeline/launchpad.py': [Errno 2] No such file or directory
[2023-04-14T22:14:21.828+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-14T22:14:21.904+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-14T22:14:21.969+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=pads, task_id=launchpad, execution_date=20230101T011500, start_date=20230414T221419, end_date=20230414T221421
[2023-04-14T22:14:22.067+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task launchpad (Bash command failed. The command returned a non-zero exit code 2.; 457)
[2023-04-14T22:14:22.132+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T22:14:22.208+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
