[2023-04-14T22:13:58.292+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pads.launchpad scheduled__2023-01-01T00:25:00+00:00 [queued]>
[2023-04-14T22:13:58.786+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pads.launchpad scheduled__2023-01-01T00:25:00+00:00 [queued]>
[2023-04-14T22:13:58.790+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:13:58.820+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-14T22:13:58.822+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:13:59.191+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): launchpad> on 2023-01-01 00:25:00+00:00
[2023-04-14T22:13:59.204+0000] {standard_task_runner.py:55} INFO - Started process 399 to run task
[2023-04-14T22:13:59.251+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pads', 'launchpad', 'scheduled__2023-01-01T00:25:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8jjtzwi6']
[2023-04-14T22:13:59.292+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask launchpad
[2023-04-14T22:14:00.396+0000] {task_command.py:389} INFO - Running <TaskInstance: pads.launchpad scheduled__2023-01-01T00:25:00+00:00 [running]> on host a0b8dfb9f67f
[2023-04-14T22:14:00.948+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Amogh Srigopal
AIRFLOW_CTX_DAG_ID=pads
AIRFLOW_CTX_TASK_ID=launchpad
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:25:00+00:00
[2023-04-14T22:14:00.953+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T22:14:00.958+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/amoghsrigopal/Downloads/SpaceDataPipeline/launchpad.py']
[2023-04-14T22:14:01.109+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T22:14:02.249+0000] {subprocess.py:93} INFO - python: can't open file '/Users/amoghsrigopal/Downloads/SpaceDataPipeline/launchpad.py': [Errno 2] No such file or directory
[2023-04-14T22:14:02.394+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-14T22:14:02.551+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-14T22:14:02.583+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=pads, task_id=launchpad, execution_date=20230101T002500, start_date=20230414T221358, end_date=20230414T221402
[2023-04-14T22:14:02.743+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task launchpad (Bash command failed. The command returned a non-zero exit code 2.; 399)
[2023-04-14T22:14:02.819+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T22:14:03.497+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
